// Display-only Greek labels for Cyprus locations.
// IMPORTANT: The DATABASE always stores English names. This map is used purely
// for rendering city/area names in the UI when the language is set to Greek.
// All filtering, search, and DB writes must continue using the English value.

const GREEK_CITY_MAP: Record<string, string> = {
  // Major cities
  "Nicosia": "Λευκωσία",
  "Limassol": "Λεμεσός",
  "Larnaca": "Λάρνακα",
  "Paphos": "Πάφος",
  "Paphos Town": "Πάφος (Πόλη)",
  "Famagusta": "Αμμόχωστος",
  "Kato Paphos": "Κάτω Πάφος",
  "Polis Chrysochous": "Πόλις Χρυσοχούς",

  // Generic
  "City Center": "Κέντρο Πόλης",
  "Tourist Area": "Τουριστική Περιοχή",
  "Coral Bay": "Κόλπος Κοραλλίων",
  "Cape Greco": "Κάβο Γκρέκο",
  "Akamas Peninsula": "Χερσόνησος Ακάμα",
  "Mackenzie": "Μακένζι",
  "Finikoudes": "Φοινικούδες",
  "Troodos": "Τρόοδος",

  // Nicosia areas
  "Strovolos": "Στρόβολος",
  "Lakatamia": "Λακατάμια",
  "Engomi": "Έγκωμη",
  "Aglantzia": "Αγλαντζιά",
  "Latsia": "Λατσιά",
  "Geri": "Γέρι",
  "Dali": "Δάλι",
  "Tseri": "Τσέρι",
  "Pallouriotissa": "Παλουριώτισσα",
  "Kaimakli": "Καϊμακλί",
  "Anthoupolis": "Ανθούπολις",
  "Makedonitissa": "Μακεδονίτισσα",
  "Deftera (Pano)": "Δευτερά (Πάνω)",
  "Deftera (Kato)": "Δευτερά (Κάτω)",
  "Kokkinotrimithia": "Κοκκινοτριμιθιά",
  "Ergates": "Εργάτες",
  "Lythrodontas": "Λυθροδόντας",
  "Psimolofou": "Ψημολόφου",
  "Peristerona": "Περιστερώνα",
  "Akaki": "Ακάκι",
  "Meniko": "Μένικο",
  "Astromeritis": "Αστρομερίτης",
  "Orounta": "Ορούντα",
  "Politiko": "Πολιτικό",
  "Pera Chorio": "Πέρα Χωριό",
  "Pera Orinis": "Πέρα Ορεινής",
  "Mammari": "Μάμμαρι",
  "Paliometocho": "Παλιομέτοχο",
  "Agios Dhometios": "Άγιος Δομέτιος",
  "Agios Sozomenos": "Άγιος Σωζόμενος",
  "Analiontas": "Ανάλιοντας",
  "Kapedes": "Καπέδες",
  "Klirou": "Κλήρου",
  "Malounta": "Μαλούντα",
  "Mathiatis": "Ματιάτης",
  "Mitsero": "Μιτσερό",
  "Nisou": "Νήσου",
  "Potamia": "Ποταμιά",
  "Sia": "Σια",
  "Lympia": "Λύμπια",
  "Kataliontas": "Καταλιόντας",
  "Kambia": "Καμπιά",
  "Kampia": "Καμπιά",
  "Lazanias": "Λαζανιάς",
  "Agrokipia": "Αγροκηπιά",
  "Arediou": "Αρεδιού",
  "Vyzakia": "Βυζακιά",
  "Xyliatos": "Ξυλιάτος",
  "Kannavia": "Κανναβιά",
  "Korakou": "Κοράκου",
  "Pera Pedi": "Πέρα Πεδί",
  "Galata": "Γαλάτα",
  "Kakopetria": "Κακοπετριά",
  "Linou": "Λινού",
  "Flasou": "Φλάσου",
  "Evrychou": "Ευρύχου",
  "Spilia": "Σπηλιά",
  "Tembria": "Τεμβριά",
  "Kalopanagiotis": "Καλοπαναγιώτης",
  "Moutoullas": "Μουτουλλάς",
  "Pedoulas": "Πεδουλάς",
  "Lagoudera": "Λαγουδερά",
  "Saranti": "Σαραντί",
  "Platanistasa": "Πλατανιστάσα",
  "Polystypos": "Πολύστυπος",
  "Alona": "Αλώνα",
  "Askas": "Ασκάς",
  "Fterikoudi": "Φτερικούδι",
  "Apliki": "Απλίκι",
  "Aplanta": "Αλάμπρα",
  "Alampra": "Αλάμπρα",
  "Kapileio": "Καπηλειό",
  "Kannaviou": "Κανναβιού",
  "Katydata": "Κατύδατα",
  "Nikitari": "Νικηταρή",
  "Farmakas": "Φαρμακάς",
  "Fikardou": "Φικάρδου",
  "Gourri": "Γούρρι",

  // Limassol areas
  "Germasogeia": "Γερμασόγεια",
  "Mesa Geitonia": "Μέσα Γειτονιά",
  "Agios Athanasios": "Άγιος Αθανάσιος",
  "Mouttagiaka": "Μουτταγιάκα",
  "Agios Tychonas": "Άγιος Τύχωνας",
  "Polemidia": "Πολεμίδια",
  "Ypsonas": "Ύψωνας",
  "Kolossi": "Κολόσσι",
  "Erimi": "Έρημη",
  "Episkopi": "Επισκοπή",
  "Akrotiri": "Ακρωτήρι",
  "Pissouri": "Πισσούρι",
  "Avdimou": "Αυδήμου",
  "Pachna": "Πάχνα",
  "Souni-Zanakia": "Σούνι-Ζανακιά",
  "Foinikaria": "Φοινικαριά",
  "Palodeia": "Παλώδεια",
  "Apsiou": "Αψιού",
  "Spitali": "Σπιτάλι",
  "Parekklisia": "Παρεκκλησιά",
  "Pyrgos": "Πύργος",
  "Pentakomo": "Πεντάκωμο",
  "Monagroulli": "Μοναγρούλλι",
  "Asgata": "Ασγάτα",
  "Vasilikos": "Βασιλικός",
  "Zygi": "Ζύγι",
  "Mari": "Μαρί",
  "Maroni": "Μαρωνί",
  "Tochni": "Τόχνη",
  "Psematismenos": "Ψεματισμένος",
  "Kalavasos": "Καλαβασός",
  "Chirokitia": "Χοιροκοιτία",
  "Skarinou": "Σκαρίνου",
  "Vavla": "Βάβλα",
  "Lefkara (Pano)": "Λεύκαρα (Πάνω)",
  "Lefkara (Kato)": "Λεύκαρα (Κάτω)",
  "Kato Drys": "Κάτω Δρυς",
  "Ora": "Όρα",
  "Melini": "Μελίνη",
  "Odou": "Οδού",
  "Kato Kivides": "Κάτω Κυβίδες",
  "Vasa Kilaniou": "Βάσα Κοιλανίου",
  "Koilani": "Κοιλάνι",
  "Lofou": "Λόφου",
  "Monagri": "Μοναγρή",
  "Silikou": "Σιλίκου",
  "Laneia": "Λάνεια",
  "Trimiklini": "Τριμίκλινη",
  "Moniatis": "Μονιάτης",
  "Platres": "Πλάτρες",
  "Pera Pedi ": "Πέρα Πεδί",
  "Agros": "Αγρός",
  "Chandria": "Χανδριά",
  "Kyperounta": "Κυπερούντα",
  "Dymes": "Δύμες",
  "Dierona": "Διερώνα",
  "Arakapas": "Αρακαπάς",
  "Akapnou": "Ακαπνού",
  "Eptagoneia": "Επταγώνεια",
  "Sykopetra": "Συκόπετρα",
  "Vikla": "Βίκλα",
  "Gerasa": "Γεράσα",
  "Paramytha": "Παραμύθα",
  "Louvaras": "Λουβαράς",
  "Kalo Chorio": "Καλό Χωριό",
  "Zoopigi": "Ζωοπηγή",
  "Salamiou": "Σαλαμιού",
  "Kellaki": "Κελλάκι",
  "Praitori": "Πραιτώρι",
  "Dora": "Δώρα",
  "Fasoula Paphou": "Φάσουλα Πάφου",
  "Episkopi Paphou": "Επισκοπή Πάφου",
  "Agios Amvrosios": "Άγιος Αμβρόσιος",
  "Agios Georgios": "Άγιος Γεώργιος",
  "Agios Nikolaos": "Άγιος Νικόλαος",
  "Zakaki": "Ζακάκι",
  "Kapsalos": "Καψάλος",

  // Larnaca areas
  "Aradippou": "Αραδίππου",
  "Livadia": "Λιβάδια",
  "Oroklini": "Ορόκλινη",
  "Pyla": "Πύλα",
  "Dhekelia": "Δεκέλεια",
  "Kiti": "Κίτι",
  "Pervolia": "Περβόλια",
  "Meneou": "Μενεού",
  "Dromolaxia": "Δρομολαξιά",
  "Kalo Chorio Larnaca": "Καλό Χωριό Λάρνακας",
  "Mazotos": "Μαζωτός",
  "Alaminos": "Αλαμινός",
  "Anafotia": "Αναφωτιά",
  "Anglisides": "Αγγλισίδες",
  "Avdellero": "Αυδελλερό",
  "Kalo Chorio (Larnaca)": "Καλό Χωριό (Λάρνακα)",
  "Kellia": "Κέλλια",
  "Klavdia": "Κλαυδιά",
  "Kofinou": "Κοφίνου",
  "Kornos": "Κόρνος",
  "Pyrga": "Πυργά",
  "Mosfiloti": "Μοσφιλωτή",
  "Tersefanou": "Τερσεφάνου",
  "Softades": "Σοφτάδες",
  "Alethriko": "Αλεθρικό",
  "Agios Theodoros": "Άγιος Θεόδωρος",
  "Athienou": "Αθηένου",
  "Avgorou": "Αυγόρου",
  "Augoros": "Αυγόρου",
  "Kivisili": "Κιβισίλι",
  "Skala": "Σκάλα",
  "Tremetousia": "Τρεμετουσιά",
  "Kalopsida": "Καλοψίδα",
  "Kokkinochoria": "Κοκκινοχώρια",

  // Famagusta areas
  "Ayia Napa": "Αγία Νάπα",
  "Protaras": "Πρωταράς",
  "Paralimni": "Παραλίμνι",
  "Deryneia": "Δερύνεια",
  "Derynia": "Δερύνεια",
  "Sotira": "Σωτήρα",
  "Frenaros": "Φρέναρος",
  "Acheritou": "Αχερίτου",
  "Achna": "Άχνα",
  "Liopetri": "Λιοπέτρι",
  "Xylofagou": "Ξυλοφάγου",
  "Xylotymbou": "Ξυλοτύμπου",
  "Vrysoules": "Βρυσούλες",
  "Vrysoulles": "Βρυσούλες",
  "Pernera": "Περνέρα",
  "Kapparis": "Κάππαρης",
  "Cape Greco ": "Κάβο Γκρέκο",
  "Makronissos": "Μακρόνησος",
  "Avgorou ": "Αυγόρου",
  "Pergamos": "Πέργαμος",
  "Dasaki Achnas": "Δασάκι Άχνας",
  "Ormideia": "Ορμίδεια",
  "Troulloi": "Τρούλλοι",
  "Tserkezoi": "Τσερκέζοι",
  "Delikipos": "Δελίκηπος",
  "Potamos Liopetriou": "Ποταμός Λιοπετρίου",
  "Agia Thekla": "Αγία Θέκλα",
  "Agia Varvara": "Αγία Βαρβάρα",
  "Agia Marinouda": "Αγία Μαρινούδα",
  "Agioi Vavatsinias": "Άγιοι Βαβατσινιάς",
  "Pomos": "Πωμός",
  "Pyrgos Tyllirias": "Πύργος Τυλληρίας",
  "Kato Pyrgos": "Κάτω Πύργος",
  "Argaka": "Αργάκα",
  "Gialia": "Γιαλιά",
  "Nea Dimmata": "Νέα Δήμματα",
  "Pachyammos": "Παχύαμμος",
  "Pomos ": "Πωμός",

  // Paphos areas
  "Geroskipou": "Γεροσκήπου",
  "Yeroskipou": "Γεροσκήπου",
  "Chloraka": "Χλώρακα",
  "Emba": "Έμπα",
  "Kissonerga": "Κισσόνεργα",
  "Konia": "Κόνια",
  "Mesogi": "Μεσόγη",
  "Tala": "Τάλα",
  "Tremithousa": "Τρεμιθούσα",
  "Tsada": "Τσάδα",
  "Stroumbi": "Στρουμπί",
  "Polemi": "Πολέμι",
  "Kallepia": "Καλλέπεια",
  "Letymbou": "Λετύμπου",
  "Choulou": "Χούλου",
  "Lemba": "Λέμπα",
  "Pegeia": "Πέγεια",
  "Peyia": "Πέγεια",
  "Latchi": "Λατσί",
  "Prodromi": "Πρόδρομη",
  "Neo Chorio": "Νέο Χωριό",
  "Drouseia": "Δρουσιά",
  "Dhrousha": "Δρούσια",
  "Inia": "Ίνια",
  "Arodes": "Αρόδες",
  "Kathikas": "Καθίκας",
  "Akoursos": "Ακούρσος",
  "Theletra": "Θελέτρα",
  "Miliou": "Μηλιού",
  "Goudi": "Γούδι",
  "Skoulli": "Σκούλλη",
  "Lasa": "Λάσα",
  "Drymou": "Δρύμου",
  "Filousa": "Φιλούσα",
  "Steni": "Στενή",
  "Kios": "Κίος",
  "Lysos": "Λυσός",
  "Peristerona Chrysochous": "Περιστερώνα Χρυσοχούς",
  "Evretou": "Ευρέτου",
  "Choli": "Χολή",
  "Kritou Marottou": "Κρίτου Μαρόττου",
  "Kritou Terra": "Κρίτου Τέρρα",
  "Anarita": "Αναρίτα",
  "Mandria": "Μανδριά",
  "Timi": "Τίμη",
  "Acheleia": "Αχέλεια",
  "Kouklia": "Κούκλια",
  "Nikokleia": "Νικόκλεια",
  "Mamonia": "Μαμμώνια",
  "Choletria": "Χολέτρια",
  "Pentalia": "Πεντάλεια",
  "Galataria": "Γαλαταριά",
  "Eledio": "Ελέδιο",
  "Amargeti": "Αμαργέτη",
  "Axylou": "Αξύλου",
  "Statos-Agios Fotios": "Στατός-Άγιος Φώτιος",
  "Panagia": "Παναγιά",
  "Kelokedara": "Κελοκέδαρα",
  "Salamiou ": "Σαλαμιού",
  "Kidasi": "Κιδάσι",
  "Praitori ": "Πραιτώρι",
  "Armou": "Άρμου",
  "Marathounta": "Μαραθούντα",
  "Koili": "Κοίλη",
  "Giolou": "Γιόλου",
  "Simou": "Σίμου",
  "Lapithiou": "Λαπίθιου",
  "Fyti": "Φύτη",
  "Lapithiou ": "Λαπίθιου",
  "Anadiou": "Αναδιού",
  "Nata": "Νάτα",
  "Choulou ": "Χούλου",
};

/**
 * Returns the localized display label for a Cyprus city/area name.
 * The original English value (used in DB and filters) is unchanged.
 *
 * @param cityName Original English city name as stored in the database
 * @param language Current i18n language code ("en" or "el")
 */
export function getCityDisplayName(cityName: string, language: string): string {
  if (!cityName) return cityName;
  if (language === "el") {
    return GREEK_CITY_MAP[cityName] || cityName;
  }
  return cityName;
}
